export const LIST_HEADERS = [
  "Customer Name",
  "Company",
  "Phone Number",
  "Email",
  "Country",
  "Status",
];

export const LIST_ITEMS = [
  {
    id: crypto.randomUUID(),
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Floyd Miles",
    company: "Yahoo",
    phone: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Ronald Richards",
    company: "Adobe",
    phone: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Marvin McKinney",
    company: "Tesla",
    phone: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Jerome Bell",
    company: "Google",
    phone: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Kathryn Murphy",
    company: "Microsoft",
    phone: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Jacob Jones",
    company: "Yahoo",
    phone: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Kristin Watson",
    company: "Facebook",
    phone: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mike Thompson",
    company: "Amazon",
    phone: "(123) 555-0199",
    email: "michael@amazon.com",
    country: "Canada",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Linda Johnson",
    company: "Apple",
    phone: "(321) 555-0123",
    email: "linda@apple.com",
    country: "Germany",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Susan Williams",
    company: "IBM",
    phone: "(456) 555-0145",
    email: "susan@ibm.com",
    country: "Australia",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Brown",
    company: "Samsung",
    phone: "(789) 555-0167",
    email: "charles@samsung.com",
    country: "South Korea",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Davis",
    company: "Intel",
    phone: "(654) 555-0189",
    email: "patricia@intel.com",
    country: "Japan",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Martinez",
    company: "Sony",
    phone: "(987) 555-0110",
    email: "david@sony.com",
    country: "Spain",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Wilson",
    company: "HP",
    phone: "(543) 555-0112",
    email: "sarah@hp.com",
    country: "France",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Moore",
    company: "Oracle",
    phone: "(210) 555-0114",
    email: "thomas@oracle.com",
    country: "India",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Taylor",
    company: "Cisco",
    phone: "(876) 555-0116",
    email: "laura@cisco.com",
    country: "Italy",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Anderson",
    company: "SAP",
    phone: "(432) 555-0118",
    email: "robert@sap.com",
    country: "Switzerland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mary Jackson",
    company: "Siemens",
    phone: "(098) 555-0120",
    email: "mary@siemens.com",
    country: "Austria",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "James White",
    company: "Uber",
    phone: "(876) 555-0122",
    email: "james@uber.com",
    country: "New Zealand",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Barbara Harris",
    company: "Lyft",
    phone: "(543) 555-0124",
    email: "barbara@lyft.com",
    country: "Netherlands",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Steven Young",
    company: "Twitter",
    phone: "(210) 555-0126",
    email: "steven@twitter.com",
    country: "Belgium",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Elizabeth Allen",
    company: "Netflix",
    phone: "(098) 555-0128",
    email: "elizabeth@netflix.com",
    country: "Sweden",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Mark Clark",
    company: "Disney",
    phone: "(876) 555-0130",
    email: "mark@disney.com",
    country: "Denmark",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Nancy Lewis",
    company: "Spotify",
    phone: "(543) 555-0132",
    email: "nancy@spotify.com",
    country: "Norway",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Paul Walker",
    company: "Slack",
    phone: "(210) 555-0134",
    email: "paul@slack.com",
    country: "Finland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Jessica Robinson",
    company: "Adobe",
    phone: "(098) 555-0136",
    email: "jessica@adobe.com",
    country: "Ireland",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Daniel Scott",
    company: "Salesforce",
    phone: "(876) 555-0138",
    email: "daniel@salesforce.com",
    country: "Portugal",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Karen Evans",
    company: "Dell",
    phone: "(543) 555-0140",
    email: "karen@dell.com",
    country: "Greece",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Brian Adams",
    company: "IBM",
    phone: "(210) 555-0142",
    email: "brian@ibm.com",
    country: "Turkey",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Jennifer Brown",
    company: "Amazon",
    phone: "(098) 555-0144",
    email: "jennifer@amazon.com",
    country: "Ukraine",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Wilson",
    company: "Apple",
    phone: "(876) 555-0146",
    email: "david@apple.com",
    country: "Poland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Susan Martinez",
    company: "Samsung",
    phone: "(543) 555-0148",
    email: "susan@samsung.com",
    country: "Hungary",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Floyd Miles",
    company: "Yahoo",
    phone: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Ronald Richards",
    company: "Adobe",
    phone: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Marvin McKinney",
    company: "Tesla",
    phone: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Jerome Bell",
    company: "Google",
    phone: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Kathryn Murphy",
    company: "Microsoft",
    phone: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Jacob Jones",
    company: "Yahoo",
    phone: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Brown",
    company: "Samsung",
    phone: "(789) 555-0167",
    email: "charles@samsung.com",
    country: "South Korea",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Davis",
    company: "Intel",
    phone: "(654) 555-0189",
    email: "patricia@intel.com",
    country: "Japan",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Martinez",
    company: "Sony",
    phone: "(987) 555-0110",
    email: "david@sony.com",
    country: "Spain",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Wilson",
    company: "HP",
    phone: "(543) 555-0112",
    email: "sarah@hp.com",
    country: "France",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Moore",
    company: "Oracle",
    phone: "(210) 555-0114",
    email: "thomas@oracle.com",
    country: "India",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Taylor",
    company: "Cisco",
    phone: "(876) 555-0116",
    email: "laura@cisco.com",
    country: "Italy",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Anderson",
    company: "SAP",
    phone: "(432) 555-0118",
    email: "robert@sap.com",
    country: "Switzerland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mary Jackson",
    company: "Siemens",
    phone: "(098) 555-0120",
    email: "mary@siemens.com",
    country: "Austria",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Brown",
    company: "Samsung",
    phone: "(789) 555-0167",
    email: "charles@samsung.com",
    country: "South Korea",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Davis",
    company: "Intel",
    phone: "(654) 555-0189",
    email: "patricia@intel.com",
    country: "Japan",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Martinez",
    company: "Sony",
    phone: "(987) 555-0110",
    email: "david@sony.com",
    country: "Spain",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Wilson",
    company: "HP",
    phone: "(543) 555-0112",
    email: "sarah@hp.com",
    country: "France",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Moore",
    company: "Oracle",
    phone: "(210) 555-0114",
    email: "thomas@oracle.com",
    country: "India",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Taylor",
    company: "Cisco",
    phone: "(876) 555-0116",
    email: "laura@cisco.com",
    country: "Italy",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Anderson",
    company: "SAP",
    phone: "(432) 555-0118",
    email: "robert@sap.com",
    country: "Switzerland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mary Jackson",
    company: "Siemens",
    phone: "(098) 555-0120",
    email: "mary@siemens.com",
    country: "Austria",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Brown",
    company: "Samsung",
    phone: "(789) 555-0167",
    email: "charles@samsung.com",
    country: "South Korea",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Davis",
    company: "Intel",
    phone: "(654) 555-0189",
    email: "patricia@intel.com",
    country: "Japan",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Martinez",
    company: "Sony",
    phone: "(987) 555-0110",
    email: "david@sony.com",
    country: "Spain",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Wilson",
    company: "HP",
    phone: "(543) 555-0112",
    email: "sarah@hp.com",
    country: "France",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Moore",
    company: "Oracle",
    phone: "(210) 555-0114",
    email: "thomas@oracle.com",
    country: "India",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Taylor",
    company: "Cisco",
    phone: "(876) 555-0116",
    email: "laura@cisco.com",
    country: "Italy",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Anderson",
    company: "SAP",
    phone: "(432) 555-0118",
    email: "robert@sap.com",
    country: "Switzerland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mary Jackson",
    company: "Siemens",
    phone: "(098) 555-0120",
    email: "mary@siemens.com",
    country: "Austria",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Brown",
    company: "Samsung",
    phone: "(789) 555-0167",
    email: "charles@samsung.com",
    country: "South Korea",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Davis",
    company: "Intel",
    phone: "(654) 555-0189",
    email: "patricia@intel.com",
    country: "Japan",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Martinez",
    company: "Sony",
    phone: "(987) 555-0110",
    email: "david@sony.com",
    country: "Spain",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Wilson",
    company: "HP",
    phone: "(543) 555-0112",
    email: "sarah@hp.com",
    country: "France",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Moore",
    company: "Oracle",
    phone: "(210) 555-0114",
    email: "thomas@oracle.com",
    country: "India",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Taylor",
    company: "Cisco",
    phone: "(876) 555-0116",
    email: "laura@cisco.com",
    country: "Italy",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Anderson",
    company: "SAP",
    phone: "(432) 555-0118",
    email: "robert@sap.com",
    country: "Switzerland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mary Jackson",
    company: "Siemens",
    phone: "(098) 555-0120",
    email: "mary@siemens.com",
    country: "Austria",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Brown",
    company: "Samsung",
    phone: "(789) 555-0167",
    email: "charles@samsung.com",
    country: "South Korea",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Davis",
    company: "Intel",
    phone: "(654) 555-0189",
    email: "patricia@intel.com",
    country: "Japan",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Martinez",
    company: "Sony",
    phone: "(987) 555-0110",
    email: "david@sony.com",
    country: "Spain",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Wilson",
    company: "HP",
    phone: "(543) 555-0112",
    email: "sarah@hp.com",
    country: "France",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Moore",
    company: "Oracle",
    phone: "(210) 555-0114",
    email: "thomas@oracle.com",
    country: "India",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Taylor",
    company: "Cisco",
    phone: "(876) 555-0116",
    email: "laura@cisco.com",
    country: "Italy",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Anderson",
    company: "SAP",
    phone: "(432) 555-0118",
    email: "robert@sap.com",
    country: "Switzerland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mary Jackson",
    company: "Siemens",
    phone: "(098) 555-0120",
    email: "mary@siemens.com",
    country: "Austria",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Brown",
    company: "Samsung",
    phone: "(789) 555-0167",
    email: "charles@samsung.com",
    country: "South Korea",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Davis",
    company: "Intel",
    phone: "(654) 555-0189",
    email: "patricia@intel.com",
    country: "Japan",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "David Martinez",
    company: "Sony",
    phone: "(987) 555-0110",
    email: "david@sony.com",
    country: "Spain",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Wilson",
    company: "HP",
    phone: "(543) 555-0112",
    email: "sarah@hp.com",
    country: "France",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Moore",
    company: "Oracle",
    phone: "(210) 555-0114",
    email: "thomas@oracle.com",
    country: "India",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Taylor",
    company: "Cisco",
    phone: "(876) 555-0116",
    email: "laura@cisco.com",
    country: "Italy",
    status: "Active",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Anderson",
    company: "SAP",
    phone: "(432) 555-0118",
    email: "robert@sap.com",
    country: "Switzerland",
    status: "Inactive",
  },
  {
    id: crypto.randomUUID(),
    name: "Mary Jackson",
    company: "Siemens",
    phone: "(098) 555-0120",
    email: "mary@siemens.com",
    country: "Austria",
    status: "Active",
  },
];
